import { chromium } from 'playwright';
const rx = /https:(?:\\\/|\\u002F|\/){2}[^"']+?\.mp4[^"']*/g;
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ storageState: './secrets/instagram_storage_state.json' });
const page = await context.newPage();
await page.goto('https://www.instagram.com/p/DRiTJUfkhtK/', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(2500);
const html = await page.content();
const matches = html.match(rx) || [];
console.log('count', matches.length);
console.log(matches[0] || 'none');
await browser.close();